### ISSUE TITLE
[OTHER] Add License

### ISSUE THREAD

**Issue by vinzvinci** [WebXDAO/webx-dao-dapp#5]
### What would you like to share?

Hey @mkubdev, I think it's good to add a license for this repo. 

### Would you like to work on this issue?

- [X] Yes, I want to work on this issue!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mkubdev** [comment]
Hi @vinzvinci, yes sure, we can use MIT :)
